### ISSUE TITLE
Setup netlify team and host our main(production) branch

### ISSUE THREAD

**Issue by hananina** [chingu-voyages/v25-geckos-team-04#13]

**Comment by hananina** [comment]
@inovux @mrpeterhanley 
Do you think we need to pay for a team account? or can we setup our project with someone's account?  

https://www.netlify.com/pricing/?_ga=2.233605403.462145429.1605231252-1875807875.1600440105

<img width="1328" alt="スクリーンショット 2020-11-13 10 55 10" src="https://user-images.githubusercontent.com/4989007/99019068-e7dccd80-259e-11eb-87d7-e793ae3f6248.png">

**Comment by mrpeterhanley** [comment]
I think its ok to host on one person's account. Since we will all have access to the repo

**Comment by inovux** [comment]
Yeah just set it up with someone's account, didn't know they asked money for this now ^^

**Comment by inovux** [comment]
@hananina I updated the `main` branch to have our current code. So let me know if you have any trouble deploying the `main` branch to netlify.

**Comment by hananina** [comment]
@inovux Ohhhh Thank you for setting this up🙏

**Comment by hananina** [comment]
Done✨ and Updated the document on Notion.
https://www.notion.so/Home-63b735b034aa4541a03e680076755228#bf3e05267f0f4555b634ee653c20a5fa
