### ISSUE TITLE
#27 Weather Card component

### ISSUE THREAD

**Issue by mrpeterhanley** [chingu-voyages/v25-geckos-team-04#27]
Uses Date component, Weather Icon component (finished), Temperature component (finished)

**Comment by hananina** [comment]
<img width="146" alt="スクリーンショット 2020-11-21 17 39 21" src="https://user-images.githubusercontent.com/4989007/99871782-83fe7880-2c20-11eb-9dfa-ddf813f7f722.png">

@mrpeterhanley @inovux I'm thinking about adding the existing components as a child element of `WeatherCard`🤔  just checking am I in the right direction? 👀 

```
<WeatherCard>
  <DateComponent date={new Date()} formatString='eee d MMM' />
  <WeatherIcon size="small" icon="heavyCloud" />
  <Temperature value={15} scale="celsius" />
</WeatherCard>
```

**Comment by mrpeterhanley** [comment]
How will the weather card know which Weather Icon component to display? Will it handle this logic itself via an input property (e.g. description) or will that be done by the parent of weather card?

**Comment by inovux** [comment]
I think you should just create the `WeatherCard` that accepts the properties that are used in the components you use there so an example to use `WeatherCard` would be:

```jsx
<WeatherCard
	date={new Date()}
	formatString='eee d MMM'
	icon="heavyCloud"
	temperature={15}
	scale="celsius"
/>
```

and then inside your `WeatherCard` component, you handle all the logic for that :)

**Comment by hananina** [comment]
Thank you @mrpeterhanley @inovux 🙏🙏 Understood that this is how it should be.. I will be handling all the logic with `WeatherCard` 🙆‍♀️
