### ISSUE TITLE
#37 City History List component

### ISSUE THREAD

**Issue by mrpeterhanley** [chingu-voyages/v25-geckos-team-04#37]
Uses City Link components

**Comment by mrpeterhanley** [comment]
@inovux @hananina I started to build this component but found it's just an empty container that holds the buttons with no need for any styling. I don't think we need this component unless there is some logic handling or functionality needed that I haven't thought of, what do you think?

**Comment by inovux** [comment]
> @inovux @hananina I started to build this component but found it's just an empty container that holds the buttons with no need for any styling. I don't think we need this component unless there is some logic handling or functionality needed that I haven't thought of, what do you think?

@mrpeterhanley This component should be responsible for the spacing between items (margins).

**Comment by mrpeterhanley** [comment]
@inovux I just applied a top / bottom margin to the button (CityLink) itself
