### ISSUE TITLE
#38 City Link component

### ISSUE THREAD

**Issue by mrpeterhanley** [chingu-voyages/v25-geckos-team-04#38]
A clickable link to display information about that city

**Comment by mrpeterhanley** [comment]
@inovux @hananina How should I implement this component? Make it a button that will generate an onClick function for a new API call for that city weather information, or a link with a Link (React router) etc. that can go to a previous saved weather history page...

**Comment by inovux** [comment]
> @inovux @hananina How should I implement this component? Make it a button that will generate an onClick function for a new API call for that city weather information, or a link with a Link (React router) etc. that can go to a previous saved weather history page...

@mrpeterhanley You can just make it a button component with `onChange` for now, since we are not sure how we want to handle the API yet and whether we want to have different pages that requires react router.

**Comment by mrpeterhanley** [comment]
@inovux Then do you think we can just use Hana's Button component with different styling or still need to make a new component?

**Comment by inovux** [comment]
I think its better to just create a new component for this one
