### ISSUE TITLE
[#63] Implement Context API for metric display

### ISSUE THREAD

**Issue by inovux** [chingu-voyages/v25-geckos-team-04#63]
We should create a context that will be responsible for the metric value: `celsius` | 'fahrenheit'. This value should be available throughout our whole application since it is used in different components.

We need to have the value, and a value setter available:

```js
{
  setMetric: () => ...,
  metric: 'celsius' | 'fahrenheit'
}
```

So you can basically use the `useState` hook for this in combination with the `createContext` [API](https://reactjs.org/docs/context.html).

**Comment by mrpeterhanley** [comment]
@inovux I created the basic context component but encountered a Typescript issue (passing the value to the context provider) and not sure what I should do here?

![context1](https://user-images.githubusercontent.com/67137187/101144952-0b51e000-3654-11eb-9aa0-4fe377af3200.png)
![context2](https://user-images.githubusercontent.com/67137187/101144966-0f7dfd80-3654-11eb-9b69-558f949060cd.png)

**Comment by inovux** [comment]
@mrpeterhanley you can give your context a type: `createContext<TYPE HERE>()`
