### ISSUE TITLE
[#65] Build WeeklyWeatherByCityContainer

### ISSUE THREAD

**Issue by inovux** [chingu-voyages/v25-geckos-team-04#65]
This container should be responsible for providing the data returned from the [5 day weather endpoint](https://openweathermap.org/forecast5).

It should also be responsible for providing a fetch function so whenever you use this component throughout the app the data can be fetched into our container.

Example API:

```jsx
<WeeklyWeatherByCityContainer
    render={({ weeklyWeather, getWeeklyWeather }) => {
        useEffect(() => {
            getWeeklyWeather('Hong Kong');
        }, [])
        return (
            // Do something with weeklyWeather data using your presentational components
        )
    }}
/>
```

Make sure you take a look at the [useReducer](https://reactjs.org/docs/hooks-reference.html#usereducer) documentation.

**Comment by hananina** [comment]
<img width="661" alt="スクリーンショット 2020-11-27 14 47 17" src="https://user-images.githubusercontent.com/4989007/100416304-78e49600-30c1-11eb-9dc0-0fb51fda54ef.png">

@inovux It's a small thing, but providing data to this container↑
Do you mean `WeeklyWeatherByCity` instead of `Hourly`🤔?

**Comment by st-currenxie** [comment]
@hananina Yeah sorry thats correct, you are right

**Comment by inovux** [comment]
@hananina Yes u are right, ill adjust that :)
