### ISSUE TITLE
Add button component

### ISSUE THREAD

**Issue by hananina** [chingu-voyages/v25-geckos-team-04#7]
- onclick
- primary or secondary

**Comment by hananina** [comment]
@mrpeterhanley @inovux 

Can we use this Button component from  `@Material-UI ` instead of adding our own Button component 😃?
since Peter-san installed it in this PR https://github.com/chingu-voyages/v25-geckos-team-04/pull/16
I think it's handy!

**Comment by mrpeterhanley** [comment]
Sure, that's fine for me either way

**Comment by inovux** [comment]
But we are only using the icons from material actually. I think it might be better to use a custom button because we might not need as much functionality as the material UI one has.

**Comment by hananina** [comment]
hmm I understand! we don't need so much variety of Material UI, so I will add a custom button😃

**Comment by hananina** [comment]
Thank you @mrpeterhanley @inovux 🙏
